// main.c
// CS210 Lesson 19 - Test driver. Do not edit this file.
//
// Reads one or more pokemon test cases from stdin and exercises
// the three functions declared in pokemon.h.
//
// Each test case is one of:
//
//   create <pokedex_num> <hp> <attack> <defense> <catch_rate> <type>
//     Build a pokemon with init_pokemon and print it.
//
//   heal <pokedex_num> <hp> <attack> <defense> <catch_rate> <type> <new_hp>
//     Build a pokemon, replace it with set_hp(pokemon, new_hp), then print it.
//
// <type> is one of: FIRE WATER GRASS ELECTRIC PSYCHIC NORMAL
//
// Lines beginning with '#' and blank lines are skipped.

#include <stdio.h>
#include <string.h>
#include "pokemon.h"
#include "tests.h"

static enum PokemonType type_from_name(const char *name) {
    if (strcmp(name, "FIRE") == 0)     return TYPE_FIRE;
    if (strcmp(name, "WATER") == 0)    return TYPE_WATER;
    if (strcmp(name, "GRASS") == 0)    return TYPE_GRASS;
    if (strcmp(name, "ELECTRIC") == 0) return TYPE_ELECTRIC;
    if (strcmp(name, "PSYCHIC") == 0)  return TYPE_PSYCHIC;
    if (strcmp(name, "NORMAL") == 0)   return TYPE_NORMAL;
    // Unrecognized: default; tests will not exercise this.
    return TYPE_NORMAL;
}

int main(void) {
    /* Built with -D RUNTESTS (make run_tests)? Run your tests and stop.
     * Without the flag the preprocessor drops this block and the program
     * runs normally. Leave this block in place. */
#ifdef RUNTESTS
    run_all_tests();
    return 0;
#endif

    char line[256];
    char op[16];
    char type_name[16];
    int pokedex_num, hp, attack, defense;
    double catch_rate;
    int new_hp;

    while (fgets(line, sizeof(line), stdin) != NULL) {
        // Skip blanks and comments
        char *p = line;
        while (*p == ' ' || *p == '\t') p++;
        if (*p == '\n' || *p == '\0' || *p == '#') continue;

        if (sscanf(p, "%15s", op) != 1) continue;

        if (strcmp(op, "create") == 0) {
            if (sscanf(p, "%15s %d %d %d %d %lf %15s",
                       op, &pokedex_num, &hp, &attack, &defense, &catch_rate, type_name) == 7) {
                pokemon_t pk = init_pokemon(pokedex_num, hp, attack, defense,
                                            catch_rate, type_from_name(type_name));
                print_pokemon(pk);
            }
        } else if (strcmp(op, "heal") == 0) {
            if (sscanf(p, "%15s %d %d %d %d %lf %15s %d",
                       op, &pokedex_num, &hp, &attack, &defense, &catch_rate,
                       type_name, &new_hp) == 8) {
                pokemon_t pk = init_pokemon(pokedex_num, hp, attack, defense, catch_rate, type_from_name(type_name));
                pk = set_hp(pk, new_hp);
                print_pokemon(pk);
            }
        }
    }
    return 0;
}
