#!/usr/bin/env bash
# CS210 Lesson 19 - local visible tests.
#
# GENERATED by scripts/build_lab_visible_tests.py. Do not hand-edit; the
# expected output is produced by running the reference solution.
#
# Builds your code and checks it against the visible test cases. These are
# a subset of what the autograder runs: passing them is necessary, not
# sufficient. Run with:  bash run_local.sh   (or: make test)

set -u
cd "$(dirname "$0")"

if [ -t 1 ]; then
    RED=$'\e[31m'; GREEN=$'\e[32m'; YELLOW=$'\e[33m'; BOLD=$'\e[1m'; RESET=$'\e[0m'
else
    RED=''; GREEN=''; YELLOW=''; BOLD=''; RESET=''
fi

trap 'rm -rf .visible_*.tmp' EXIT

pass=0; fail=0
report() {  # report <name> <expected_file> <actual_file>
    if diff -q "$2" "$3" >/dev/null 2>&1; then
        echo "${GREEN}PASS${RESET} $1"; pass=$((pass + 1))
    else
        echo "${RED}FAIL${RESET} $1"
        awk -v bold="$BOLD" -v reset="$RESET" '
            BEGIN { ne = 0; ng = 0 }
            NR == FNR { want[FNR] = $0; ne = FNR; next }
                      { got[FNR] = $0; ng = FNR }
            END {
                n = (ne > ng) ? ne : ng
                shown = 0
                for (i = 1; i <= n; i++) {
                    if ((i in want) && (i in got) && want[i] == got[i])
                        continue
                    if (++shown > 10) {
                        print "  ...more differences not shown"
                        break
                    }
                    printf "  %sline %d:%s\n", bold, i, reset
                    if (i in want)
                        printf "    expected: %s\n", want[i]
                    else
                        printf "    expected: (nothing - your output has extra lines)\n"
                    if (i in got)
                        printf "    yours:    %s\n", got[i]
                    else
                        printf "    yours:    (missing - your output ended early)\n"
                }
            }' "$2" "$3"
        fail=$((fail + 1))
    fi
}

finish() {
    echo
    echo "${BOLD}=== Summary ===${RESET}"
    echo "${GREEN}$pass passed${RESET}, ${RED}$fail failed${RESET}"
    [ $fail -eq 0 ] && exit 0 || exit 1
}
echo "${BOLD}=== Build ===${RESET}"
# `make pokemon` (not plain `make`): before the cadet writes their rules, the
# stub's only target is `test` itself, and plain make would recurse into
# this script forever.
BIN=./pokemon
rm -f pokemon
make_log=$(make pokemon 2>&1)
if [ -x ./pokemon ]; then
    echo "${GREEN}OK${RESET} (built by your Makefile)"
else
    echo "${YELLOW}make did not produce ./pokemon - building with plain gcc instead.${RESET}"
    echo "  (The Makefile is part of the lab. make said:)"
    echo "$make_log" | head -6 | sed 's/^/    | /'
    # Build under a scratch name: `pokemon` itself must only ever come from
    # the cadet's Makefile (the autograder checks that make produces it).
    BIN=./.visible_bin.tmp
    if ! gcc -Wall -Werror -g -o .visible_bin.tmp main.c pokemon.c; then
        echo "${RED}Compile failed.${RESET} Fix the errors above, then rerun."
        exit 1
    fi
fi
echo
echo "${BOLD}=== Visible tests ===${RESET}"
"$BIN" < 'tests/sample/input1.txt' > .visible_actual.tmp 2>/dev/null
report 'sample1' 'tests/sample/expected1.txt' .visible_actual.tmp
"$BIN" < 'tests/sample/input2.txt' > .visible_actual.tmp 2>/dev/null
report 'sample2' 'tests/sample/expected2.txt' .visible_actual.tmp
"$BIN" < 'tests/sample/input3.txt' > .visible_actual.tmp 2>/dev/null
report 'sample3' 'tests/sample/expected3.txt' .visible_actual.tmp
echo
echo "${BOLD}=== Your tests (test_lab19.c) ===${RESET}"
if gcc -Wall -Werror -g -D RUNTESTS -o .visible_tests.tmp main.c test_lab19.c pokemon.c; then
    if ./.visible_tests.tmp > .visible_tests_out.tmp 2>&1; then
        echo "${GREEN}PASS${RESET} your tests (every assert held, exit 0)"; pass=$((pass + 1))
    else
        echo "${RED}FAIL${RESET} your tests: an assert failed or the program exited non-zero"
        tail -n 6 .visible_tests_out.tmp | sed 's/^/    | /'
        fail=$((fail + 1))
    fi
else
    echo "${RED}FAIL${RESET} test_lab19.c did not compile. Fix the errors above, then rerun."
    fail=$((fail + 1))
fi
finish
